/**
 *  Analog Bridge — HTML to C Header Converter
 *
 *  Reads the Vite build output (dist/index.html), gzips it,
 *  and writes a C header file with the data as a const uint8_t array.
 *
 *  Usage: node scripts/embed.js
 *  Output: ../esp32/src/web/web_data.h
 */
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const inputFile = path.join(__dirname, '..', 'dist', 'index.html');
const outputFile = path.join(__dirname, '..', '..', 'esp32', 'src', 'web', 'web_data.h');

if (!fs.existsSync(inputFile)) {
  console.error(`Error: ${inputFile} not found. Run 'vite build' first.`);
  process.exit(1);
}

const html = fs.readFileSync(inputFile);
const gzipped = zlib.gzipSync(html, { level: 9 });

console.log(`HTML size:    ${html.length} bytes`);
console.log(`Gzipped size: ${gzipped.length} bytes`);
console.log(`Ratio:        ${((1 - gzipped.length / html.length) * 100).toFixed(1)}% reduction`);

// Convert to C hex array
const hexArray = Array.from(gzipped)
  .map(b => `0x${b.toString(16).padStart(2, '0')}`)
  .reduce((lines, hex, i) => {
    if (i % 16 === 0) lines.push([]);
    lines[lines.length - 1].push(hex);
    return lines;
  }, [])
  .map(line => '  ' + line.join(', '))
  .join(',\n');

const header = `/**
 *  Analog Bridge — Dashboard HTML (auto-generated)
 *
 *  DO NOT EDIT — this file is generated by scripts/embed.js
 *  Source: firmware/web-ui/src/index.html
 *  Build:  cd firmware/web-ui && npm run build
 *
 *  HTML size:    ${html.length} bytes
 *  Gzipped size: ${gzipped.length} bytes
 */
#ifndef AB_WEB_DATA_H
#define AB_WEB_DATA_H

#include <Arduino.h>

static const uint8_t index_html_gz[] PROGMEM = {
${hexArray}
};
static const size_t index_html_gz_len = ${gzipped.length};

#endif // AB_WEB_DATA_H
`;

fs.writeFileSync(outputFile, header);
console.log(`Written to: ${outputFile}`);
